namespace Amethyst.Abstractions.Worlds;

public enum Biome : byte
{
    Ocean,
    Plains,
    Desert,
    ExtremeHills,
    Forest,
    Taiga,
    Swampland,
    River,
    Hell,
    Sky,
    FrozenOcean,
    FrozenRiver,
    IcePlains,
    IceMountains,
    MushroomIsland,
    MushroomShore,
    Beach,
    DesertHills,
    ForestHills,
    TaigaHills,
    SmallMountains,
    Jungle,
    JungleHills,
    JungleEdge,
    DeepOcean,
    StoneBeach,
    ColdBeach,
    BirchForest,
    BirchForestHills,
    RoofedForest,
    ColdTaiga,
    ColdTaigaHills,
    MegaTaiga,
    MegaTaigaHills,
    ExtremeHillsPlus,
    Savanna,
    SavannaPlateau,
    Mesa,
    MesaPlateauForest,
    MesaPlateau,
    SunflowerPlains = 129,
    DesertMountains = 130,
    ExtremeHillsMountains = 131,
    FlowerForest = 132,
    TaigaMountains = 133,
    SwamplandMountains = 134,
    IcePlainsSpikes = 140,
    JungleMountains = 149,
    JungleEdgeMountains = 151,
    BirchForestMountains = 155,
    BirchForestHillsMountains = 156,
    RoofedForestMountains = 157,
    ColdTaigaMountains = 158,
    MegaSpruceTaiga = 160,
    MegaSpruceTaigaHills = 161,
    ExtremeHillsPlusMountains = 162,
    SavannaMountains = 163,
    SavannaPlateauMountains = 164,
    MesaBryce = 165,
    MesaPlateauForestMountains = 166,
    MesaPlateauMountains = 167
}